[package]
name = "getset"
description = """
Getset, we're ready to go!

A procedural macro for generating the most basic getters and setters on fields.
"""
version = "0.0.4"
authors = ["hoverbear <andrew@hoverbear.org>"]
license = "MIT"

categories = ["development-tools::procedural-macro-helpers"]
keywords = ["macro", "getter", "setter", "getters", "setters"]
readme = "README.md"
repository = "https://github.com/Hoverbear/getset"

[badges]
travis-ci = { repository = "https://github.com/Hoverbear/getset" }
appveyor = { repository = "https://github.com/Hoverbear/getset", service = "github" }

[lib]
proc-macro = true

[dependencies]
quote = "0.3.15"
syn = "0.11.11"

